//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string Article { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductSupplier { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductCategory { get; set; }
        public int ProductDiscount { get; set; }
        public int QuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }

        public string StringInfoCombined
        {
            get
            {
                return Article + "; " + ProductName + "; " + Unit + "; " + ProductSupplier + 
                    "; " + ProductManufacturer + "; " + ProductCategory + "; " + ProductDescription;
            }
        }

        public string PhotoPath
        {
            get
            {
                if (ProductPhoto != null)
                    return @"img\" + ProductPhoto;
                else
                    return null;
            }
        }

        public string FullPhotoPath
        {
            get
            {
                if (ProductPhoto != null)
                {
                    return @"E:\VS Projects\4 курс\Shoes\Shoes\img\" + ProductPhoto;
                }
                else
                    return null;
            }
        }

        public string OldPrice
        {
            get
            {
                if (this.ProductDiscount > 0)
                {
                    return this.ProductPrice.ToString();
                }
                else
                    return "";
            }
        }

        public decimal PriceWDiscount
        {
            get
            {
                if (this.ProductDiscount > 0)
                {
                    double newPrice = (double)this.ProductPrice - (double)this.ProductPrice * this.ProductDiscount / 100.0;

                    return Convert.ToDecimal(string.Format("{0:F2}", newPrice));
                        //Math.Round(newPrice,2,MidpointRounding.AwayFromZero);
                }
                else
                    return this.ProductPrice;
            }
        }

        public SolidColorBrush ProductEntryBG
        {
            get
            {
                if (this.ProductDiscount > 15)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("#2E8B57");
                }
                else
                {
                    if (this.QuantityInStock < 1)
                    {
                        return (SolidColorBrush)new BrushConverter().ConvertFromString("LightBlue");
                    }
                    else
                    {
                        return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                    }
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
